### ISSUE TITLE
اشکال در سطوح دسترسی با استفاده از کاربر ویندوز

### ISSUE THREAD

**Issue by irajchardoli** [VahidN/DNTIdentity#15]
با سلام
ضمن تشکر از پروژه عالی شما ، در رابطه با اعتبار سنجی با استفاده از کاربر ویندوز ، من یک یوزر با نام کابر ویندوزم ایجاد کردم و همچنین نقش ادمین رو هم به این یوزر دادم.
در حالتی که من بدون استفاده از فرم لاگین از سیستم استفاده می کنم با پیغام عدم دسترسی به فرم مربوطه مواجه میشوم در حالیکه کاربر من ادمین هست.
طبق بررسی که انجام دادم متوجه شدم که در کانتکست
 RoleClaimType
مقدار زیر را دارد:
http://schemas.microsoft.com/ws/2008/06/identity/claims/groupsid

در صورتی که مقادیر نقش ها با کلید
 http://schemas.microsoft.com/ws/2008/06/identity/claims/role
 در
 claim 
 ثبت شده است و این موضوع باعث میگردد.

```
        public bool CanUserAccess(ClaimsPrincipal user, string area, string controller, string action)
        {
            var currentClaimValue = $"{area}:{controller}:{action}";
            var securedControllerActions = _mvcActionsDiscoveryService.GetAllSecuredControllerActionsWithPolicy(ConstantPolicies.DynamicPermission);
            if (!securedControllerActions.SelectMany(x => x.MvcActions).Any(x => x.ActionId == currentClaimValue))
            {
                throw new KeyNotFoundException($@"The `secured` area={area}/controller={controller}/action={action} with `ConstantPolicies.DynamicPermission` policy not found. Please check you have entered the area/controller/action names correctly and also it's decorated with the correct security policy.");
            }

            if (!user.Identity.IsAuthenticated)
            {
                return false;
            }

            if (user.IsInRole(ConstantRoles.Admin))
            {
                // Admin users have access to all of the pages.
                return true;
            }

            // Check for dynamic permissions
            // A user gets its permissions claims from the `ApplicationClaimsPrincipalFactory` class automatically and it includes the role claims too.
            return user.HasClaim(claim => claim.Type == ConstantPolicies.DynamicPermissionClaimType &&
                                          claim.Value == currentClaimValue);
        }
```

User.IsInRole 
همیشه 
False 
بر میگرداند.

در صورتی که در این زمینه راهنمایی بفرمایید ممنون می شوم.

**Comment by VahidN** [comment]
<div dir="rtl">

به اين مطالب نياز داريد
[فعالسازی Windows Authentication در برنامه‌های ASP.NET Core 2.0 ](http://www.dotnettips.info/post/2762)
[ApplicationClaimsTransformation ](https://github.com/VahidN/DNTIdentity/blob/master/src/ASPNETCoreIdentitySample.Services/Identity/ApplicationClaimsTransformation.cs)

**Comment by irajchardoli** [comment]
جناب آقای نصیری
من مطالب سایت شما رو دنبال می کنم و مطلب مد نظر شما رو هم خوندم ، سناریویی که من توضیح دادم با استفاده از همین پروژه بدون کوچکترین تغییری می باشد ، صرفا اعتبارسنجی بر اساس ویندوز را فعال کردم.

ApplicationClaimsTransformation
به طور کامل انجام میشود و تمام نقش های کاربر از دیتابیس خوانده و به کلیم کاربر کاربر اضافه می شود.
نقش های کاربر با کلید
http://schemas.microsoft.com/ws/2008/06/identity/claims/role
به کلیم کابر اضافه میشود.

مشکل 
user.IsInRole()
هست که همیشه 
False 
برمیگرداند
که من فکر میکنم به خاطر مقدار
RoleClaimType
می باشد.

```
AuthenticationType = NTLM => RoleClaimType = http://schemas.microsoft.com/ws/2008/06/identity/claims/groupsid

AuthenticationType = Identity.Application => RoleClaimType = http://schemas.microsoft.com/ws/2008/06/identity/claims/role

```

**Comment by irajchardoli** [comment]
با اضافه کردن نقش های کاربر به کلیم به صورت زیر مشکل حل میشود:

```
        private async Task<IEnumerable<Claim>> addExistingUserClaimsAsync(IIdentity identity)
        {
           ...

            if (_userManager.SupportsUserRole)
            {
                var roles = await _userManager.GetRolesAsync(user).ConfigureAwait(false);
                foreach (var roleName in roles)
                {
                    claims.Add(new Claim(Options.RoleClaimType, roleName));                    

                    if(identity.AuthenticationType == "NTLM")    **//Added**
                        claims.Add(new Claim(ClaimTypes.GroupSid, roleName));    **//Added**

                    ...
                }
            }

            return claims;
        }
```
با این تغییر متد
user.IsInRole("xxx")
مقدار درست را برمیگرداند.
