### ISSUE TITLE
بررسی مجدد بخش ثبت نام در پروژه

### ISSUE THREAD

**Issue by miladsoft** [VahidN/DNTIdentity#17]
با سلام . در هنگام ثبت نام وقتی نام کاربری درج میشود و هنوز ایمیلی وارد نشده است پیام خطای ولیدیشن ایمیل را میدهد و به نظر بنده این بخش نیاز به ویرایش دارد . 
![firefox_2018-03-04_00-31-25](https://user-images.githubusercontent.com/6504337/36939304-d1b68ec4-1f43-11e8-927b-316856766db8.png)

**Comment by VahidN** [comment]
<div dir="rtl">

 سلام؛‌ اين مورد بيشتر به طراحى خود وليدتور اين فريم ورك مرتبط هست كه همه را يكجا و با هم نياز دارد. بنابراين بايد با آن به همين نحو زندگى كرد مگر اينكه در فريم ورك اصلى اين جداسازى‌ها انجام شوند. userValidator كل اطلاعات شىء كاربر را اعتبارسنجى مي‌كند و تمام فيلدهاى آن‌‌را با هم
