### ISSUE TITLE
عدم سرو شدن فایل های استاتیک زمان پابلیش

### ISSUE THREAD

**Issue by minaakh** [VahidN/DNTIdentity#18]
<div dir="rtl">

سلام
فایل های استاتیک من در زمان دولوپ مشکلی ندارن و همه سرو میشن ولی وقتی پابلیش میکنم دیگه فایل های استاتیک سرو نمیشن و خطای 410 داده میشه و اونها رو پیدا نمیکنه.

همین طور من به جای 
bower.json
اومدم از
package.json
هم استفاده کردم و دستور 
npm i
 رو زدم و بعد 
bundleconfig.json
رو بر مبنای 
node_modules
به روز کردم و در نهایت هم 
```
app.UseFileServer(new FileServerOptions
            {
                FileProvider = new PhysicalFileProvider(Path.Combine(Directory.GetCurrentDirectory(), "bower_components")),
                RequestPath = "/bower_components",
                EnableDirectoryBrowsing = false
            });
```
رو به
```
app.UseFileServer(new FileServerOptions
            {
                FileProvider = new PhysicalFileProvider(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot")),
                RequestPath = "/wwwroot",
                EnableDirectoryBrowsing = false
            });
```
تغییر دادم چون اگر از 
```
   RequestPath = "/bower_components",
```
یا
```
   RequestPath = "/node_modules",
```
استفاده میکردم زمان پابلیش خطا میداد که فولدر وجود نداره

ولی در این 2 حالت هم باز فایل های استاتیک سرو نمیشن

**Comment by VahidN** [comment]
<div dir="rtl">
دستور زير را در ريشه‌ي پروژه‌ي وب اجرا كنيد

dotnet publish -c Release

اين دستور خطاهاي احتمالي را نمايش مي‌دهد و در اينجا محل پوشه‌ي نود اهميتي ندارد چون باندلر فقط دو فايل
wwwroot\js
wwwroot\css
را توليد مي‌كند و برنامه فقط از اين دو فايل استفاده مي‌كند. اگر تنظيمات باندلر را صحيح وارد نكرده باشيد، اين دو فايل توليد نمي‌شوند

**Comment by minaakh** [comment]
<div dir="rtl">

ممنون ولی با دستور فوق هم خطا ندارم و فقط وارنینگ دارم 
تنظیمات باندلر رو هم تغییری داخلش ندادم

**Comment by VahidN** [comment]
<div dir="rtl">

تنظيمات [فايل پروايدر](https://github.com/VahidN/DNTIdentity/blob/master/src/ASPNETCoreIdentitySample/Startup.cs#L78) اينجا اساسا اضافي هستند چون فايل layout برنامه فقط دو فايل زير را استفاده مي‌كند

[css/site.min.css](https://github.com/VahidN/DNTIdentity/blob/master/src/ASPNETCoreIdentitySample/Views/Shared/_Layout.cshtml#L12)
[js/site.min.js](https://github.com/VahidN/DNTIdentity/blob/master/src/ASPNETCoreIdentitySample/Views/Shared/_Layout.cshtml#L90)

اين دو فايل هم حاصل كار باندلر هستند و مطلقا نيازي به پابليش پوشه‌ي اضافي ديگري نيست. همينقدر كه اين دو فايل را در wwwroot داشته باشيد، برنامه كار مي‌كند. 
تنظيمات اضافه‌تر را هم حذف كنيد

بنابراين شما بايد بررسي كنيد كه چه فايل‌هايي در فايل layout مدخلي دارند. در اينجا فقط و فقط اين دو فايل هستند كه حاصل پردازش و يكي كردن ده‌ها فايل از مسيرهاي مختلف هستند
اين دو فايل بايد در پابليش نهايي حضور داشته باشند و مطابق آزمايش من حضور دارند

**Comment by VahidN** [comment]
<div dir="rtl">

پروژه براي استفاده از ان پي ام به روز شد
