### ISSUE TITLE
عوض کردن پوشه bower component

### ISSUE THREAD

**Issue by hofa77** [VahidN/DNTIdentity#2]
سلام جناب نصیری 
ابتدا بابت این پروژه که به اشتراک گذاشتید ازتون قدردانی میکنم

یه سوال
چطوری باید مسیر نصب کامپوننت های 
bower
روی عوض کنم و تنظیمش کنم
چون وقتی آپدیت میکنم
خودش میره توی پوشه
wwroot 
نصب میشه 

ممنون بازم

**Comment by VahidN** [comment]
<div dir="rtl">

آن مسير استاندارد هست. چيزي كه سبب به روز رساني پوشه‌ي wwwroot مي‌شود، مباحث Bundling & minification هستند:
[ ارتقاء به ASP.NET Core 1.0 - قسمت 21 - بررسی تغییرات Bundling و Minification](http://www.dotnettips.info/post/2471/%d8%a7%d8%b1%d8%aa%d9%82%d8%a7%d8%a1-%d8%a8%d9%87-asp-net-core-1-0-%d9%82%d8%b3%d9%85%d8%aa-21-%d8%a8%d8%b1%d8%b1%d8%b3%db%8c-%d8%aa%d8%ba%db%8c%db%8c%d8%b1%d8%a7%d8%aa-bundling-%d9%88-minification)
