### ISSUE TITLE
عدم نمایش خطای اعتبارسنجی نام کاربری و ایمیل به جای یکدیگر

### ISSUE THREAD

**Issue by minaakh** [VahidN/DNTIdentity#20]
با سلام
آیا امکانش هست که اعتبارسنجی مربوط به نام کاربری و ایمیل با هم نباشند و جدا از هم باشند؟ چون در حال حاضر در صورت معتبر نبودن یکی، پیام خطای مربوطه برای فیلد دیگر هم نمایش داده میشود

**Comment by VahidN** [comment]
https://github.com/VahidN/DNTIdentity/issues/17
