### ISSUE TITLE
actionDescriptor.RouteValues["area"] چک خالی بودن؟

### ISSUE THREAD

**Issue by mahdisky** [VahidN/DNTIdentity#21]
سلام 
این مقدار 
var area = actionDescriptor.RouteValues["area"]; 
جایی برای خالی یا پر بودن چک میشه؟
چون در حالت عادی این مقدار خالی هست و خطا میگیره

**Comment by VahidN** [comment]
هدفش اين بوده كه نشان دهد چطور مي‌توان به اين مقادير دسترسي يافت
 در اين برنامه مشكلي نداشته. در برنامه‌ي شما اگر مشكل داره خوب بررسي‌اش كنيد
