### ISSUE TITLE
netcore2.1 یا netstandard2.1

### ISSUE THREAD

**Issue by Marjani** [VahidN/DNTIdentity#22]
<div dir="rtl">

سلام، شما برای خود پروژه وب از نوع دات نت کر 2.1 استفاده می کنید و برای کلاس لایبرری ها از نت استاندارد؟
ممکنه در این مورد توضیح بدید که چرا این کار رو می کنید؟
چرا از دانت کر برای کلاس لایبرری ها استفاده نمی کنید؟

**Comment by VahidN** [comment]
<div dir="rtl">

اگر از بسته [Microsoft.AspNetCore.App](https://www.nuget.org/packages/Microsoft.AspNetCore.App) .استفاده كنيد نياز به دات نت كر دارد
در كل رسم هست كه هميشه از سطح وابستگي كمتر شروع كرد. اطلاعات بيشتر
https://www.dotnettips.info/newsarchive/details/11470
https://www.dotnettips.info/newsarchive/details/11467
https://www.dotnettips.info/post/2733
