### ISSUE TITLE
امکان لاگین به جای کاربر دیگر

### ISSUE THREAD

**Issue by Marjani** [VahidN/DNTIdentity#23]
سلام
اگر ممکن هست امکان لاگین مدیر به جای کاربران دیگر و بازگشت به پنل خودش را به پروژه اضافه کنید.
یا اگر امکان داره راهنمایی بفرمایید، تا در توسعه این قسمت مشارکت کنیم.
با تشکر

**Comment by VahidN** [comment]
<div dir="rlt">
در مورد User impersonation تحقيق كنيد
