### ISSUE TITLE
 ioc configin in WCF service application

### ISSUE THREAD

**Issue by Katy-kh** [VahidN/DNTIdentity#24]
<div dir="rtl">

سلام آقای نصیری
من یک پروژه WCF Service Application به سولوشن اضافه کردم، میخواستم بدونم چطور میتونم به ApplicationDbContext دسترسی داشته باشم ، آیا امکان استفاده از  IocConfig برای تزریق وابستگی ها توی پروژه Wcf Service هست ؟
من از  Windosr استفاده کردم و به کانستراکتور سرویسم  IUnitOfWork را اضافه کردم اما وابستگی
Ef Core رو چطور باید در این پروژه انجام بدم؟
پیشاپیش خیلی از راهنماییتون متشکرم

**Comment by Katy-kh** [comment]
من تونستم با استفاده از
ApplicationDbContextFactory
یک کانتکست در 
wcf service
بسازم و بتونم روی دیتابیس  کوئری بزنم.
حالا سوال من اینه که چطور میتونم به سرویس ها یعنی پروژه
Services
دسترسی داشته باشم و وابستگی های اونارو 
Resolve
کنم؟

**Comment by ArmaSa** [comment]
سلام
من هم همین مشکل رو دارم.
آیا امکان حل این مسله وجود داره.

ممنون از شما.

**Comment by VahidN** [comment]
<div dir="rtl">

مثال‌تان را همينجا آپلود كنيد تا بررسي كنم. در اين اديتور درگ و دراپ فايل‌ها هم كار مي‌كند
