### ISSUE TITLE
update to bootstrap 4?

### ISSUE THREAD

**Issue by minaakh** [VahidN/DNTIdentity#25]
Hi,
would you please update this project to bootstrap 4 rtl?

**Comment by VahidN** [comment]
Not yet. I'm waiting for the result of this official topic: https://github.com/twbs/bootstrap/issues/24807

**Comment by VahidN** [comment]
it's done via #https://github.com/VahidN/DNTIdentity/commit/9dd1d0f7ff90c78231de30440297b2e007980b88
