### ISSUE TITLE
how to remove email from identity

### ISSUE THREAD

**Issue by minaakh** [VahidN/DNTIdentity#27]
Hi,
I dont need email in my register so I want to know how can I remove email from register?
even when I removed validateEmail method from ValidateAsync method, I get InvalidEmail when I dont have email in my form from?

**Comment by VahidN** [comment]
[It's explained here](https://www.dotnettips.info/post/2579/%d8%b3%d9%81%d8%a7%d8%b1%d8%b4%db%8c-%d8%b3%d8%a7%d8%b2%db%8c-asp-net-core-identity-%d9%82%d8%b3%d9%85%d8%aa-%d8%b3%d9%88%d9%85-%d9%86%d8%b1%d9%85%d8%a7%d9%84-%d8%b3%d8%a7%d8%b2%d9%87%d8%a7-%d9%88-%d8%a7%d8%b9%d8%aa%d8%a8%d8%a7%d8%b1%d8%b3%d9%86%d8%ac%e2%80%8c%d9%87%d8%a7#comment-15985).

**Comment by mmv68** [comment]
RequireUniqueEmail = false  //<-- the default is true
یه همچین تنظیمی در 
ApplicationUserManager
انجام دهید دیگر نیاز به ورود ایمیل نخواهید داشت
