### ISSUE TITLE
authorization in razor code

### ISSUE THREAD

**Issue by mmv68** [VahidN/DNTIdentity#28]
<div dir="rtl">

عرض سلام  و ادب احترام جهت اعمال دسترسی در بین کدهای کندو نیاز به استفاده از کدی همانند
User.Identity.IsInrole("SomeRole")
دارم با تگی که شما گذاشتید نمیشه این کارو انجام داد ایا میشه توسط همچین کدی کنترلر و اکشن رو فرستاد و با یک 
if
ساده چک کرد
باتشکر

**Comment by VahidN** [comment]
<div dir="rtl">

User.IsInRole‌ در اينجا هم قابل استفاده است. [يك مثال](https://github.com/VahidN/DNTIdentity/blob/master/src/ASPNETCoreIdentitySample/Views/Shared/_Layout.cshtml#L35)

اگر خواستيد از سياست‌هاي دسترسي هم استفاده كنيد مي‌شود از IAuthorizationService استفاده كرد. توضيحات  بيشتر آن در قسمت
 « [بررسی نحوه‌ی استفاده‌ی از Authorization Policy تعریف شده و جایگزین کردن آن با روش بررسی نقش‌ها](https://www.dotnettips.info/post/2910) » كه چون جزو استانداردهاي ASP.NET Core است در مثال جاري هم كار مي‌كند
