### ISSUE TITLE
CreateAsync inside CustomUserClaimsPrincipalFactory doesn't get called

### ISSUE THREAD

**Issue by SirwanAfifi** [VahidN/DNTIdentity#3]
I'm going to store some additional claims into the database, I followed you blog post ([part 4](http://www.dotnettips.info/post/2580/%D8%B3%D9%81%D8%A7%D8%B1%D8%B4%DB%8C-%D8%B3%D8%A7%D8%B2%DB%8C-asp-net-core-identity-%D9%82%D8%B3%D9%85%D8%AA-%DA%86%D9%87%D8%A7%D8%B1%D9%85-user-claims)) But I couldn't get it to work. Here's step I followed:
- Created my own implementation of  `IUserClaimsPrincipalFactory<TUser>`:
```
public class ApplicationClaimsPrincipalFactory : UserClaimsPrincipalFactory<User, IdentityRole>
{
	public static readonly string ClubId = nameof(ClubId);

	public ApplicationClaimsPrincipalFactory(
	UserManager<User> userManager,
	RoleManager<IdentityRole> roleManager,
	IOptions<IdentityOptions> optionsAccessor) : base(userManager, roleManager, optionsAccessor)
	{
	}

	public override async Task<ClaimsPrincipal> CreateAsync(User user)
	{
		var principal = await base.CreateAsync(user); // adds all `Options.ClaimsIdentity.RoleClaimType -> Role Claims` automatically + `Options.ClaimsIdentity.UserIdClaimType -> userId` & `Options.ClaimsIdentity.UserNameClaimType -> userName`
		addCustomClaims(user, principal);
		return principal;
	}

	private static void addCustomClaims(User user, IPrincipal principal)
	{
		((ClaimsIdentity)principal.Identity).AddClaims(new[]
		{
			new Claim(ClaimTypes.NameIdentifier, user.Id.ToString(), ClaimValueTypes.Integer),
			new Claim(ClaimTypes.GivenName, user.FirstName ?? string.Empty),
			new Claim(ClaimTypes.Surname, user.LastName ?? string.Empty),
			// adding clubId to the claim
			new Claim(ClubId, user.ClubId.ToString(), ClaimValueTypes.String),
		});
	}
}
```
- Registered the custom factory (I added this registration after `services.AddIdentity()` call):
```
services.AddScoped<IUserClaimsPrincipalFactory<User>, ApplicationClaimsPrincipalFactory>();
services.AddScoped<UserClaimsPrincipalFactory<User, IdentityRole>, ApplicationClaimsPrincipalFactory>();
```

But when I seed my database with this code:
```
var userAddResult = Task.Run(() => _userManager.CreateAsync(new User
{
	FirstName = x.FirstName,
	LastName = x.LastName,
	Email = x.Email,
	UserName = x.Username,
	Avatar = x.Avatar
}, x.Password)).Result;
```
`CreateAsync` method inside the custom factory doesn't get called.

**PS**: I also commented `AddEntityFrameworkStores` I also have [this step](https://github.com/VahidN/DNTIdentity/issues/1) in my application.

Is there other additional step that I must add in order to have this functionality?

Thanks 👍

**Comment by VahidN** [comment]
`CreateAsync` of `ApplicationClaimsPrincipalFactory` class will be called during the signing phase (when the user logs in)

<div dir="rtl">
همان قسمت « ASP.NET Core Identity چگونه اطلاعات جدول AppUserClaims را پردازش می‌کند؟ »
