### ISSUE TITLE
افزودن Middleware برای CSP(Content-Security Policy)

### ISSUE THREAD

**Issue by Hamidnch** [VahidN/DNTIdentity#32]
<div dir="rtl">

سلام.وقت بخیر.
ابتدا تشکر از پروژه خیلی خوبتون.
میخواستم خواهش کنم اگر ممکنه در پروژه جاری مدیریت CSP رو هم قرا بدین.

تشکر

**Comment by VahidN** [comment]
Added via #https://github.com/VahidN/DNTIdentity/commit/d56b1cea552c196c24cf936e2e0381ca13d64b9d
