### ISSUE TITLE
logging

### ISSUE THREAD

**Issue by kaktoosii** [VahidN/DNTIdentity#34]
<div dir="rtl">

سلام آقای نصیری
توی این پروژه شما از logging استفاده کردیدولی چطور میشه اون رو طوری کانفیگ کرد که  
LogLevel.Information هم ثبت کنه
الان با تغییر توی startup.cs پروژه خطا میده

**Comment by VahidN** [comment]
<div dir="rtl">

در حالت information اطلاعات زيادي لاگ مي‌شود. [به همين جهت نياز به يك صف داشت](https://github.com/VahidN/DNTIdentity/commit/4df4f6792176d5e8d4aad3863773ae0f0c8d1e21) تا سبب كرش برنامه نشود.
