### ISSUE TITLE
Coretests

### ISSUE THREAD

**Issue by kaktoosii** [VahidN/DNTIdentity#35]
<div dir="rtl">

سلام توی لایه تست 
قسمت coretests با database provider
مشکل داره آیا باید تغییری داد

**Comment by VahidN** [comment]
Fixed it via #https://github.com/VahidN/DNTIdentity/commit/65f67cbcd56a2e7052bf2c27cc3c8df093ad3e13

**Comment by kaktoosii** [comment]
ممنون آقای نصیری امکان داره یه نمونه تست برای  کنترلر ها برای اکشن get یا list بنویسید
