### ISSUE TITLE
 عدم نمایش ظاهر سایت

### ISSUE THREAD

**Issue by omid68** [VahidN/DNTIdentity#36]
<div dir="rtl">

با سلام
سپاسگزارم از شما بایت اشتراک گذاری این پروژه
ببخشید شاید سوالم ابتدایی باشه ولی وقتی که این پروژه رو اجرا میکنم انگار که فایل های
css
به درستی لود نمیشن و ظاهر سایت به خوبی نمایش داده نمیشه
ممنون میشم بنده رو راهنمایی بفرمائید

**Comment by VahidN** [comment]
<div dir="rtl">

نياز هست فايل‌هاي [package.json](https://github.com/VahidN/DNTIdentity/blob/master/src/ASPNETCoreIdentitySample/package.json) آن دريافت شوند. براي اينكار فايل [restore.bat](https://github.com/VahidN/DNTIdentity/blob/master/src/ASPNETCoreIdentitySample/_0-restore.bat) را اجرا كنيد

**Comment by omid68** [comment]
با سلام مجدد
.سپاسگزارم از پاسخگویی تون ممنونم
