### ISSUE TITLE
مدیریت لاگ

### ISSUE THREAD

**Issue by rbsdotnet** [VahidN/DNTIdentity#39]
جناب نصیری سوالی داشتم
من لاگ رو براساس مستندات این پروژه پیاده سازی کردم
مشکلی که الان به وجود اومده هر لحظه در جدول لاگ این رکوردها ذخیره میشه و باعث کند شدن سیستم میشه
[Log.txt](https://github.com/VahidN/DNTIdentity/files/3293483/Log.txt)

1 | 2019-06-16 00:03:14.6550548 | 10403 |   | Information | Microsoft.EntityFrameworkCore.Infrastructure | Entity Framework Core 2.2.4-servicing-10062 initialized 'ApplicationDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: MaxPoolSize=128 CommandTimeout=180 using NetTopologySuite | [  {    "Key": "version",    "Value": "2.2.4-servicing-10062"  },  {    "Key": "contextType",    "Value": "ApplicationDbContext"  },  {    "Key": "provider",    "Value": "Microsoft.EntityFrameworkCore.SqlServer"  },  {    "Key": "options",    "Value": "MaxPoolSize=128 CommandTimeout=180 using NetTopologySuite "  },  {    "Key": "{OriginalFormat}",    "Value": "Entity Framework Core {version} initialized '{contextType}' using provider '{provider}' with options: {options}"  }] | NULL | NULL | 2019-06-15 19:33:16.7030948 +00:00 | NULL | NULL | NULL | <Binary data>
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

ممنون میشم راهنمایی کنید

**Comment by rbsdotnet** [comment]
زمانی که این دستور رو اضافه میکنم این لاگ ها تولید میشه
            services.AddEntityFrameworkSqlServerNetTopologySuite();
از این دستور برای location استافده میکنم

**Comment by VahidN** [comment]
<div dir="rtl">

شما [سطح لاگ Information](https://github.com/VahidN/DNTIdentity/blob/master/src/ASPNETCoreIdentitySample/appsettings.json#L10) را داريد ثبت مي‌كنيد. [اين سطح](https://github.com/VahidN/DNTIdentity/blob/master/src/ASPNETCoreIdentitySample/Program.cs#L41) را تغيير دهيد.
[اطلاعات بيشتر در مورد سطوح لاگ](https://www.dotnettips.info/post/2467)
