### ISSUE TITLE
 migration fails

### ISSUE THREAD

**Issue by AshkanAlavi** [VahidN/DNTIdentity#4]
عرض ادب
 بعد از به روز رسانی به نسخه 2017 امکان ایجاد یا به روز رسانی مایگریشن وجود نداره 
خطا:
`D:\DNTIdentity-master\src\ASPNETCoreIdentitySample\obj\ASPNETCoreIdentitySample.csproj.EntityFrameworkCore.targets(4,5): error MSB4006: There is a circular dependency in the target dependency graph involving target "GetEFProjectMetadata". [D:\DNTIdentity-master\src\ASPNETCoreIdentitySample\ASPNETCoreIdentitySample.csproj]
Unable to retrieve project metadata. Ensure it's an MSBuild-based .NET Core project. If you're using custom BaseIntermediateOutputPath or MSBuildProjectExtensionsPath values, Use the --msbuildprojectextensionspath option.`

**Comment by VahidN** [comment]
Fixed via https://github.com/VahidN/DNTIdentity/commit/76a7b4da373a27d0e395bed22585a64c80a31b3f
