### ISSUE TITLE
تغییر رمز عبور توسط مدیر سایت

### ISSUE THREAD

**Issue by RezaAVS** [VahidN/DNTIdentity#40]
<div dir="rtl"> 
سلام
به چه صورت میشه رمز بور کاربران توسط مدیرسایت تغییر کنه؟

در MVC من از این روش استفاده کردم و جواب میداد

<div dir="ltr"> 

```
var userModel = await _users.FirstOrDefaultAsync(row => row.Code == changePasswordViewModel.Code);
var applicationUserStoreService = new ApplicationUserStoreService(_unitOfWork.GetContext());
await applicationUserStoreService.SetPasswordHashAsync(userModel, PasswordHasher.HashPassword(changePasswordViewModel.Password));
await applicationUserStoreService.UpdateAsync(userModel);
```

**Comment by VahidN** [comment]
<div dir="rtl">

حتما اطلاع داريد كه اين پروژه [يك قسمت تغيير كلمه‌ي عبور كاربر جاري](https://github.com/VahidN/DNTIdentity/blob/master/src/ASPNETCoreIdentitySample/Areas/Identity/Controllers/ChangePasswordController.cs#L73) را هم دارد. بعد در همانجا در كد پياده سازي آن، كاربر جاري يافت مي‌شود و كلمه‌ي عبور او تغيير مي‌كند. فقط همان سطر را به سطر يافتن كاربر مدنظر تغيير دهيد

**Comment by RezaAVS** [comment]
<div dir="rtl">
بله این بخش رو مطالعه کردم منظورم این بود که ادمین بتواند تغییر رمز عبور برای هرکاربری را انجام دهد
در روش بالا باید رمز عبور جاری باشد
اما ادمین رمز عبور جاری کاربر را که ندارد. 
روشی که بدون دانستن پسورد جاری، پسورد کاربر تغییر کند

**Comment by VahidN** [comment]
<div dir="rtl">

كدش را دنبال كنيد، به [UpdatePasswordHash](https://github.com/aspnet/AspNetCore/blob/394eb3ca13c662e1c2288372e05f46fbcb149c16/src/Identity/Extensions.Core/src/UserManager.cs#L2401) خواهيد رسيد
