### ISSUE TITLE
Jwt

### ISSUE THREAD

**Issue by AliHaydari** [VahidN/DNTIdentity#43]
<div dir="rtl">

سلام
تلاش کردم دو پروژه DNTIdentity و ASPNETCore2JwtAuthentication را با هم ترکیب کنم
نیاز پروژه به این صورت هست که هم کلاینت های موبایلی داشته باشه و هم وب
مشکلات زیادی پیش اومده
مثلا برای کاربران سمت وب در یک area جدید، قسمت حذف که به صورت مودال و ایجکسی هست اررور 500 میده ولی بقیه قسمت ها که submit میشوند درست کار میکنند!
نیاز دارم اگر امکانش را دارید راهنمایی بفرمایید که مراحل اضافه کردن درست jwt به پروژه به چه صورت و ترتیبی هست تا مشکلات سیستم را برطرف کنم

**Comment by AliHaydari** [comment]
سلام مجدد
پس از اضافه کردن jwt به پروژه در قسمت

`_httpContextAccessor.HttpContext.RequestServices.GetRequiredService<IHttpRequestInfoService>();`

با کاربر وب برای یک درخواست ایجکسی(درخواست حذف) در یک area جدید 2تا خطا میدهد

`context (Parameter 'Value cannot be null or empty.')`

و

`context (Parameter 'Value cannot be null or empty.') at Microsoft.AspNetCore.Mvc.Routing.UrlHelperFactory.GetUrlHelper(ActionContext context)`

همه چیز در area Identity درست کار میکند!

**Comment by VahidN** [comment]
<div dir="rtl">

اين پروژه قسمت ديگري نخواهد داشت. همچنين من كارهاي شخصي را هم پشتيباني نمي‌كنم
اگر در پروژه‌ي قست issues وجود دارد، فقط و فقط مرتبط به كار آن شخص است و نه هيچ پروژه‌ي ثالث ديگري
