### ISSUE TITLE
توضیح در مورد کلاس DynamicPermissionsAuthorizationHandler

### ISSUE THREAD

**Issue by AliHaydari** [VahidN/DNTIdentity#44]
سلام
در کلاس DynamicPermissionsAuthorizationHandler.cs
خط زیر تا پایان بلوک شرط
https://github.com/VahidN/DNTIdentity/blob/8fe4a56b509692dc451b10c874c3f5506e3f94a0/src/ASPNETCoreIdentitySample.Services/Identity/DynamicPermissionsAuthorizationHandler.cs#L48

شرطی که اضافه کردین دلیلش چیه و چه کاربردی داره؟

**Comment by VahidN** [comment]
<div dir="rtl">

فقط يك مثال هست براي دريافت اطلاعات از فرم يا روش‌هاي ديگر. اين موارد در پرسش و پاسخ‌هاي مطلب متناظر با آن در سايت هست

**Comment by AliHaydari** [comment]
سلام مجدد
پس از اضافه کردن jwt به پروژه در قسمت

_httpContextAccessor.HttpContext.RequestServices.GetRequiredService<IHttpRequestInfoService>();

با کاربر وب برای یک درخواست ایجکسی(درخواست حذف) در یک area جدید 2تا خطا میدهد

context (Parameter 'Value cannot be null or empty.')

و

context (Parameter 'Value cannot be null or empty.') at Microsoft.AspNetCore.Mvc.Routing.UrlHelperFactory.GetUrlHelper(ActionContext context)

همه چیز در area Identity درست کار میکند!
