### ISSUE TITLE
خطا در هاست اشتراکی

### ISSUE THREAD

**Issue by xdegian** [VahidN/DNTIdentity#45]
من با پروژه فوق چندین سیستم توسعه داده ام 
و به تازگی ورژن 3.1.1 دا دانلود کردم و  پروژه جدیدی بر روی آن توسعه دادم
که پروژه در لوکال بخوبی کار میکند اما بر رو هاست اشتراکی خطا میدهد که با فعال کردن لاگ از  وب کانفیگ خطای زیر را میگیرم
قابل ذکر است حتی پروژه خام را هم که پابلیش میگیرم  و در هاست قرار میدهم همین خطا رو میگیرم

> Unhandled exception. System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: ASPNETCoreIdentitySample.Services.Contracts.Identity.IEmailSender Lifetime: Scoped ImplementationType: ASPNETCoreIdentitySample.Services.Identity.AuthMessageSender': Unable to resolve service for type 'DNTCommon.Web.Core.IWebMailService' while attempting to activate 'ASPNETCoreIdentitySample.Services.Identity.AuthMessageSender'.) (Error while validating the service descriptor 'ServiceType: ASPNETCoreIdentitySample.Services.Contracts.Identity.ISmsSender Lifetime: Scoped ImplementationType: ASPNETCoreIdentitySample.Services.Identity.AuthMessageSender': Unable to resolve service for type 'DNTCommon.Web.Core.IWebMailService' while attempting to activate 'ASPNETCoreIdentitySample.Services.Identity.AuthMessageSender'.) (Error while validating the service descriptor 'ServiceType: ASPNETCoreIdentitySample.Services.Contracts.Identity.ISecurityTrimmingService Lifetime: Scoped ImplementationType: ASPNETCoreIdentitySample.Services.Identity.SecurityTrimmingService': Unable to resolve service for type 'DNTCommon.Web.Core.IMvcActionsDiscoveryService' while attempting to activate 'ASPNETCoreIdentitySample.Services.Identity.SecurityTrimmingService'.) (Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Authorization.IAuthorizationHandler Lifetime: Scoped ImplementationType: ASPNETCoreIdentitySample.Services.Identity.DynamicPermissionsAuthorizationHandler': Unable to resolve service for type 'DNTCommon.Web.Core.IMvcActionsDiscoveryService' while attempting to activate 'ASPNETCoreIdentitySample.Services.Identity.SecurityTrimmingService'.) (Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Authorization.IAuthorizationService Lifetime: Transient ImplementationType: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService': Unable to resolve service for type 'DNTCommon.Web.Core.IMvcActionsDiscoveryService' while attempting to activate 'ASPNETCoreIdentitySample.Services.Identity.SecurityTrimmingService'.) (Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Authorization.IAuthorizationHandlerProvider Lifetime: Transient ImplementationType: Microsoft.AspNetCore.Authorization.DefaultAuthorizationHandlerProvider': Unable to resolve service for type 'DNTCommon.Web.Core.IMvcActionsDiscoveryService' while attempting to activate 'ASPNETCoreIdentitySample.Services.Identity.SecurityTrimmingService'.) (Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Authorization.Policy.IPolicyEvaluator Lifetime: Transient ImplementationType: Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator': Unable to resolve service for type 'DNTCommon.Web.Core.IMvcActionsDiscoveryService' while attempting to activate 'ASPNETCoreIdentitySample.Services.Identity.SecurityTrimmingService'.)

**Comment by VahidN** [comment]
<div dir="rtl">

تمام خطاهايي كه دريافت كرديد مرتبط با [DNTCommon.Web.Core](https://github.com/VahidN/DNTIdentity/search?q=DNTCommon&unscoped_q=DNTCommon) است كه عنوان مي‌كند سرويس‌هاي آن ثبت نشده‌اند

<div dir="ltr">

```C#
services.AddDNTCommonWeb();
```

**Comment by xdegian** [comment]
سیستم در لوکال کاملا صحیح کار میکند
در هاست اشتراکی این خطا ر میگیرم

**Comment by VahidN** [comment]
<div dir="rtl">
بررسي كنيد تفاوت خروجي دستور زير بر روي سيستم خودتان و هاست چيست؟

<div dir="ltr">

```
dotnet --list-sdks
```

**Comment by xdegian** [comment]
چون هاست اشتراکی بود هاست همکاذی لازم رو نکرد و من نمی تونم نتیجه درستور فوق رو بدونم
پس از گرفتن پابلیش با دستور 
dotnet
میتونستم روژن های پایین پروژه رو اجرا بگیرم ولی تو ورژن 3 و بالاتر اجرا نمیده

**Comment by VahidN** [comment]
<div dir="rtl">

الان آخرين نگارش 3.1.2 هست. از هاست درخواست كنيد كه [فايل‌هاي مرتبط ](https://www.dotnettips.info/post/2869/%da%a9%d8%af%d8%a7%d9%85%db%8c%da%a9-%d8%a7%d8%b2-%d8%a8%d8%b3%d8%aa%d9%87%e2%80%8c%d9%87%d8%a7%db%8c-net-core-%d8%b1%d8%a7-%d8%a8%d8%a7%db%8c%d8%af-%d8%af%d8%b1%db%8c%d8%a7%d9%81%d8%aa-%da%a9%d9%86%db%8c%d9%85)را نصب كند
