### ISSUE TITLE
افزودن پروایدر Sms برای TFA

### ISSUE THREAD

**Issue by rbsdotnet** [VahidN/DNTIdentity#46]
<div dir="rtl">
سلام جناب نصیری
توی این پروژه میخواستم پروایدر SMS رو اضافه کنم برای تایید 2 عاملی
این پروایدر رو در چه بخشی باید register  کنم؟
سپاس از شما

**Comment by VahidN** [comment]
<div dir="rtl">

[در اينجا](https://github.com/VahidN/DNTIdentity/blob/master/src/ASPNETCoreIdentitySample.Services/Identity/AuthMessageSender.cs#L14)

**Comment by rbsdotnet** [comment]
<div dir="rtl">
منظورم این بخش هست

<div dir="ltr">
` manager.RegisterTwoFactorProvider("PhoneCode", new PhoneNumberTokenProvider<ApplicationUser>
    {
        MessageFormat = "Your security code is: {0}"
    });`

**Comment by VahidN** [comment]
<div dir="rtl">

چنين بخشي در نگارش core [وجود خارجي ندارد](https://github.com/dotnet/aspnetcore/search?q=RegisterTwoFactorProvider&unscoped_q=RegisterTwoFactorProvider) و نيازي به اينكار نيست. تنها قسمتي كه بايد تكميل شود همين سرويسي كه نام برده شد به علاوه دريافت شماره تماس از شخص كه [در اينجا](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/2fa?view=aspnetcore-1.1) توضيح داده شده
