### ISSUE TITLE
SecurityStampValidator Not Run

### ISSUE THREAD

**Issue by rbsdotnet** [VahidN/DNTIdentity#47]
<div dir="rtl">
سلام جناب نصیری

من از ساختار پروژه شما استفاده کردم اما وارد این بخش نمی شود
تمام روال ها رو بررسی کردم از تزریق وابستگی ها تا خود پیاده سازی کلاس ها دقیقا مثل شما هست
اما در پروژه خودم وارد این بخش نمی شود تا آخرین ورود کاربر رو ذخیره کند.
ممنون میشم راهنمایی کنید

**Comment by rbsdotnet** [comment]
<div dir="rtl">
مشکل برطرف شدبه خاطر یکی بود نام این کلاس با کلاس ساخته شده من در پروژه بود

**Comment by rbsdotnet** [comment]
@VahidN 
<div dir="rtl">
سلام جناب نصیری
باعرض پوزش
بعد از تغییر نام مشکل برطرف شد. اما بعد از لاگ اوت و لاگین مجدد دیگر این وارد کلاس CustomSecurityStampValidator نشد.
بعد از بررسی پروژه شما با هربار refresh وارد کلاس ApplicationClaimsPrincipalFactory می شود اما در پروژه من چنین اتفاقی رخ نمی دهد فقط بعد از اولین لاگین روی می دهد
ممنون میشم راهنمایی کنید

**Comment by VahidN** [comment]
<div dir="rtl">

تنظيم [enableImmediateLogout](https://github.com/VahidN/DNTIdentity/blob/35e7d498764b6e57577cb59ce9c1d2210abae4da/src/ASPNETCoreIdentitySample.IocConfig/AddIdentityOptionsExtensions.cs#L64) را داريد؟

**Comment by rbsdotnet** [comment]
<div dir="rtl">
بله
<div dir="ltr">

` private static void EnableImmediateLogout(this IServiceCollection services)
        {
            services.Configure<SecurityStampValidatorOptions>(options =>
            {
                options.ValidationInterval = TimeSpan.Zero;
                options.OnRefreshingPrincipal = principalContext => Task.CompletedTask;
            });
        }`

**Comment by rbsdotnet** [comment]
<div dir="rtl">
من کلاس CookieAuthenticationEvents برای داشتن 2 لاگین مختلف به صورت custome نوشتم و تابع 
RedirectToLogin
رو override  کردم
و متد SetApplicationCookieOptions به صورت زیر استفاده کردم
            identityOptionsCookies.Events = new CustomCookieAuthenticationEvent();
وقتی فعال هست کار نمی کنه وقتی کامنت میکنم درست کار میکنه
