### ISSUE TITLE
افزایش زمان اجرای درخواست در آپلود فایل

### ISSUE THREAD

**Issue by sbrfarhadi** [VahidN/DNTIdentity#49]
<p dir='rtl' align='right'>
با سلام
پروژه رو روی iis منتشر کردم
برای آپلود فایل تنظیم زیر رو انجام دادم و محدودیت حجم آپلود رو  نامحدود گذاشتم
</p>

```
public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<IISServerOptions>(options =>
            {
                options.MaxRequestBodySize = null;
            });

            services.AddControllersWithViews();
        }
```
<p dir='rtl' align='right'>
و توی وب کانفیگ تنظیم زیر رو گذاشتم
</p>

```
<security>
    <requestFiltering>
      <!-- This will handle requests up to 300MB -->
      <requestLimits maxAllowedContentLength="314572800" />
    </requestFiltering>
  </security>
```
<p dir='rtl' align='right'>
 و توی تگ aspNetCore تو فایل وب کانفیگ هم حالت هاستینگ رو inprocess تنظیم هستش
چطوری requestTimeout رو باید بیشتر از 2 دقیقه کنم
</p>
<p dir='rtl' align='right'>
کد <httpRuntime executionTimeout="3000" /> فایل وب کنفیگ که توی asp.net mvc استفاده میشد هم اینجا عمل نمیکنه
</p>
<p dir='rtl' align='right'>
توی تگ aspNetCore وب کانفیگ خصوصیت requestTimeout هست که اونم کار نکرد
</p>

```
.NET Core SDK version: 3.1
IDE: 
```

**Comment by VahidN** [comment]
<div dir="rtl">

[اين تنظيمات](https://www.dotnettips.info/post/2555/%d8%a8%d8%b1%d8%b1%d8%b3%db%8c-%d8%b1%d9%88%d8%b4-%d8%a2%d9%be%d9%84%d9%88%d8%af-%d9%81%d8%a7%db%8c%d9%84%e2%80%8c%d9%87%d8%a7-%d8%af%d8%b1-asp-net-core#comment-15731) را بررسي كنيد.

**Comment by sbrfarhadi** [comment]
<p dir='rtl' align='right'>
بسیار ممنونم از شما، یک پروژه خالی از asp core ایجاد کردم و تنظیمات لینک ارسالی شما رو براش گذاشتم و توی IIS منتشر کردم
</p>
<p dir='rtl' align='right'>
جالب برام اینه که فقط با کد زیر مشکل تایم اوت حل میشه و خصوصیت requestTimeout داخل تگ aspNetCore تاثیری نذاشت، درحالیکه این کد هیچ نشانی برای تایم اوت نداشت
</p>
services.Configure<FormOptions>(options =>
            {
                options.ValueLengthLimit = int.MaxValue;
                options.MultipartBodyLengthLimit = long.MaxValue; // <-- ! long.MaxValue
                options.MultipartBoundaryLengthLimit = int.MaxValue;
                options.MultipartHeadersCountLimit = int.MaxValue;
                options.MultipartHeadersLengthLimit = int.MaxValue;
            });
