### ISSUE TITLE
پیاده سازی تراکنش در پروژه

### ISSUE THREAD

**Issue by mohsen77sk** [VahidN/DNTIdentity#50]
ممنون میشم اگه یه نمونه تراکنش درپروژه پیاده سازی کنید.

**Comment by VahidN** [comment]
<div dir="rtl">

تمام اعمال EF Core تراكنشي هستند. اما اگر نياز به ايجاد تراكنش صريح وجود داشت از [متدهاي زير](https://github.com/VahidN/DNTIdentity/blob/master/src/ASPNETCoreIdentitySample.DataLayer/Context/IUnitOfWork.cs#L28) استفاده كنيد:

<div dir="ltr">

```C#
void BeginTransaction();
void RollbackTransaction();
void CommitTransaction();
```

**Comment by mohsen77sk** [comment]
من با این ارور مواجه میشم
System.InvalidOperationException: The configured execution strategy 'SqlServerRetryingExecutionStrategy' does not support user initiated transactions. Use the execution strategy returned by 'DbContext.Database.CreateExecutionStrategy()' to execute all the operations in the transaction as a retriable unit.
...

**Comment by VahidN** [comment]
<div dir="rtl">

سطر [EnableRetryOnFailure](https://github.com/VahidN/DNTIdentity/blob/master/src/ASPNETCoreIdentitySample.DataLayer.MSSQL/MsSqlServiceCollectionExtensions.cs#L32) مربوط به تراكنش‌هاي ضمني خودش است. براي تراكنش‌هاي صريح مي‌توانيد آن‌را حذف كنيد.
