### ISSUE TITLE
Login status lost

### ISSUE THREAD

**Issue by Anushiravani** [VahidN/DNTIdentity#54]
<div dir="rtl">

تمامی قسمت هارو درست کار میکنن ولی وقتی اپلیکیشن پول خالی میشه یا خود IIS ریست میشه تمامی یوز پسورد ها از بین میره . این مورد وقتی یوزر هامون زیاده داره اذیت میکنه با توجه به اینکه من سیستم ورود رو با پیامک گذاشتم هزینه هم داره برای من زیاد میشه . ممکنه بفرمایید مشکل از کجاست ؟ سرور ویندوز 2016 هست و ازهمین پروژه استفاده شده make-cert رو انجام دادم ولی بازم از بین میره لوگین کاربرا

**Comment by VahidN** [comment]
<div dir="rtl">

اين مطلب را پيگيري كنيد:

https://www.dotnettips.info/post/2717/
