### ISSUE TITLE
اجرا نشدن پابلیش

### ISSUE THREAD

**Issue by Jabbariii** [VahidN/DNTIdentity#55]
# Summary of the issue
آخرین نسخه رو بدون تغییر بصورت 
X64
پابلیش میگیرم رو هاست اجرا نمیشه
حتی خوایتم رو کنسول با  دستور 
dotnet
اجرا کنم بازم اجرا نشد
خطایی هم نشون نمیده

## Environment

```
.NET Core SDK version: 
IDE: 
```

## Example code/Steps to reproduce:

```
paste your core code
```

## Output:

```
Exception message:
Full Stack trace:
```

**Comment by VahidN** [comment]
<div dir="rtl">
[اين مطلب را پيگيري كنيد](https://www.dntips.ir/post/2829/%d8%a8%d8%b1%d8%b1%d8%b3%db%8c-%d8%ae%d8%b7%d8%a7%d9%87%d8%a7%db%8c-%d9%85%d9%85%da%a9%d9%86-%d8%af%d8%b1-%d8%ad%db%8c%d9%86-%d8%b1%d8%a7%d9%87-%d8%a7%d9%86%d8%af%d8%a7%d8%b2%db%8c-%d8%a7%d9%88%d9%84%db%8c%d9%87-%d8%a8%d8%b1%d9%86%d8%a7%d9%85%d9%87%e2%80%8c%d9%87%d8%a7%db%8c-asp-net-core-%d8%af%d8%b1-iis)
