### ISSUE TITLE
.NET 5 and Template

### ISSUE THREAD

**Issue by KiarashS** [VahidN/DNTIdentity#56]
Thanks for such a useful project.

Does this project support .NET 5?
Is there any project template powered by this project?

**Comment by VahidN** [comment]
- Yes, `SDK-5.0.302` in the readme file means supporting .NET 5.
- Yes. It has [a way to create](https://github.com/VahidN/DNTIdentity/blob/master/_register_template.bat) a new template. [More info](https://www.dntips.ir/post/2724/%d8%a7%d9%85%da%a9%d8%a7%d9%86-%d8%b3%d8%a7%d8%ae%d8%aa-%d9%82%d8%a7%d9%84%d8%a8-%d8%a8%d8%b1%d8%a7%db%8c-%d9%be%d8%b1%d9%88%da%98%d9%87%e2%80%8c%d9%87%d8%a7%db%8c-net-core).

**Comment by KiarashS** [comment]
Thanks a lot!
@VahidN What about .NET 6?
