### ISSUE TITLE
حذف متد CheckArgumentIsNull

### ISSUE THREAD

**Issue by shahrivar137** [VahidN/DNTIdentity#57]
سلام
ممنون بابت مثال کاربردی که ارائه کردید. 
دلیل حذف این متد در ورژن جدید چیه؟ چون الان در همه متدهای سازنده باید بررسی نال بودن انجام بشه...
```
public static void CheckArgumentIsNull(this object o, string name)
{
    if (o == null)
        throw new ArgumentNullException(name);
}
```
اگر متد زیر رو داشته باشیم کمکی میکنه؟
```
public static T CheckArgument<T>(this T obj)
{
    return obj ?? throw new ArgumentNullException(typeof(T).Name);
}
```
```
public LoginController(IApplicationSignInManager signInManager)
{
    _signInManager = signInManager.CheckArgument();
}
```

**Comment by VahidN** [comment]
اين نوع متدها با امكانات [nullable reference types](https://www.dntips.ir/post/3042/c-8-0-nullable-reference-types) سازگاري ندارند و توسط كامپايلر قابليت شناسايي بررسي نال بودن را ندارند چون به همراه يك سري annotation مخصوص نيستند. اگر مي‌خواهيد با متدها كار كنيد، روش استاندارد كار آن در دات نت 6 با استفاده از [ArgumentNullException.ThrowIfNull](https://www.dntips.ir/post/1060/%d8%a8%d9%87-%d8%af%d8%b3%d8%aa-%d8%a2%d9%88%d8%b1%d8%af%d9%86-%d8%a7%d8%b7%d9%84%d8%a7%d8%b9%d8%a7%d8%aa-%da%a9%d8%af-%d8%a7%d8%ac%d8%b1%d8%a7%da%a9%d9%86%d9%86%d8%af%d9%87-%db%8c%da%a9-%d9%85%d8%aa%d8%af#comment-18710) هست.
