### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by arminprv** [VahidN/DNTIdentity#58]
# Summary of the issue

با سلام
من میخواستم برای این پروژه در محیط لینوکس Dockerfile آماده کنم، برای همین دستورات و به ترتیب میزنم تا پروژه بیلد بشه اما در مرحله آخر هیچ اتفاقی نمیوفته و پورتی بالا نمیاد.
شما برای این پروژه Dockerfile آماده ای دارین؟
با تشکر

## Environment

```
.NET Core SDK version:  7.0.102
OS: Linux Ubuntu 20.04
```

## Example code/Steps to reproduce:

```
dotnet tool update -g Microsoft.Web.LibraryManager.Cli
libman restore src/ASPNETCoreIdentitySample
dotnet restore src/ASPNETCoreIdentitySample
dotnet publish -c Release -o out
dotnet ASPNETCoreIdentitySample.dll
```

## Output:

```

```

**Comment by VahidN** [comment]
سلام؛ بانك اطلاعاتي پيش‌فرض اين پروژه [localdb هست](https://github.com/VahidN/DNTIdentity/blob/master/src/ASPNETCoreIdentitySample/appsettings.json#L71) و بر روي ويندوز آزمايش شده. البته قابل تغيير هست. بهتر است يكبار اين تغييرات را اعمال كنيد و به صورت معمولي آن‌را اجرا كنيد. پس از صحت عمليات، آن‌را به سيستم عامل‌هاي ديگر هم مي‌شود منتقل كرد.
