### ISSUE TITLE
Sending Json instead of Form Data in DynamicPermission 

### ISSUE THREAD

**Issue by paradisehuman** [VahidN/DNTIdentity#6]
سلام این کد اجرا میشه و مشکلی ندارم.
```c#
 [HttpPost]
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        [ActionName("Test")]
        public ActionResult Test([FromForm] string model)
        {
            return Json("ok");
        }
```
چطور میشه به جای ارسال فرم دیتا، جیسن ارسال کرد ؟
```c#
 [HttpPost]
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        [ActionName("Test")]
        public ActionResult Test([FromBody] string model)
        {
            return Json("ok");
        }
```
وقتی جیسن ارسال میکنم این ارور رو بهم میده :

>   An unhandled exception occurred while processing the request
>   InvalidOperationException: Incorrect Content-Type: application/json
>   Microsoft.AspNetCore.Http.Features.FormFeature.ReadForm()

**Comment by VahidN** [comment]
Follow [Index([FromBody]RoleViewModel model)](https://github.com/VahidN/DNTIdentity/blob/master/src/ASPNETCoreIdentitySample/Controllers/DynamicPermissionsTestController.cs#L26) and  [function postData()](https://github.com/VahidN/DNTIdentity/blob/master/src/ASPNETCoreIdentitySample/Views/DynamicPermissionsTest/Index.cshtml#L17).
 [More info](http://www.dotnettips.info/post/2468/%d8%a7%d8%b1%d8%aa%d9%82%d8%a7%d8%a1-%d8%a8%d9%87-asp-net-core-1-0-%d9%82%d8%b3%d9%85%d8%aa-18-%da%a9%d8%a7%d8%b1-%d8%a8%d8%a7-asp-net-web-api)
