### ISSUE TITLE
Update-Database Failed

### ISSUE THREAD

**Issue by parisapoursani** [VahidN/DNTIdentity#61]
با سلام

در زمان Update-Database پیام "There is already an object named 'AppDataProtectionKeys' in the database." نوشته می شود. و database تشکیل نمیشود.
![image (2)](https://user-images.githubusercontent.com/121706347/218178103-0340cffa-2ccf-4505-96c9-820210a221fb.png)

**Comment by VahidN** [comment]
اين مساله [دلايل زيادي](https://stackoverflow.com/questions/26305273/there-is-already-an-object-named-in-the-database) منجمله تغيير فضاي نام و امثال آن‌را دارد. چون داريد برنامه را آزمايش مي‌كنيد، يكبار فايل‌هاي پوشه‌ي migrations را منهاي فايل editorconfig. آن پاك كنيد. بعد بانك اطلاعاتي فعلي آزمايشي را هم drop كنيد. مجددا migrations را توليد و اعمال كنيد.
