### ISSUE TITLE
duplicate insert in table AppUserUsedPasswords

### ISSUE THREAD

**Issue by nikanf** [VahidN/DNTIdentity#63]
# Summary of the issue

insert duplicate row in table "AppUserUsedPasswords" after add new user
![AppUserUsedPasswords](https://github.com/user-attachments/assets/34397f94-9ec8-4304-8ed5-097455ab3628)

## Environment
windows 10
MS SQL server express 2019
```
.NET Core SDK version:  8
IDE:  visual studio 2022

**Comment by VahidN** [comment]
Overriding `CreateAsync(User user, string password)` was unnecessary.
