### ISSUE TITLE
اشکال در تنظیم سطوح دسترسی پویا

### ISSUE THREAD

**Issue by rezaeiy** [VahidN/DNTIdentity#7]
سلام
تشکر بابت پروژه خیلی خوبتون
در قسمت اختصاص دسترسی به نقش ها موقع افزودن دسترسی نقش به اکشن متدها مشکلی وجود نداره ولی اگه بخوایم تمامی دسترسی هایی رو که به یک نقش دادیم از آن نقش بگیریم امکان پذیر نیست در حالی که پیغام موفقیت آمیز بودن عملیات رو هم نشون میده.
اگه یکی یکی دسترسی ها رو بگیریم و ذخیره کنیم باز حداقل یک دسترسی باقی می ماند.

**Comment by VahidN** [comment]
Fixed via https://github.com/VahidN/DNTIdentity/commit/43947e7dbef8971a4f6abfc6931e3dbe049f6048
