### ISSUE TITLE
grid sample

### ISSUE THREAD

**Issue by h4m3d66** [VahidN/DNTIdentity#9]
با سلام و تشکر فراوان بابت به اشتراک گذاری پروژه
میخواستم اگر براتون مقدور هست یک سمپل گرید ساده هم به پروژه اضافه بفرمایید مثلا برای محصولات که موجودیت ها و سرویس هاش هم موجود هست
با تشکر

**Comment by VahidN** [comment]
قسمت نقش‌ها و ويرايش آن‌ها يك جدول هست به همراه ويرايش
قسمت نمايش لاگ خطاهاي سيستم جدول هست به همراه صفحه بندي

**Comment by h4m3d66** [comment]
تشکر اون موارد رو دیده بودم
منظورم گریدی هست که قابلیت استفاده مجدد و همچنین فیلتر، سورت و پیجینگ رو هم داشته باشه
مثل گرید تلریک یا Grid.Mvc  یا ...

**Comment by VahidN** [comment]
<div dir="rtl">
من چنين قصدي ندارم و خارج است از موضوع اين پروژه
